

import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';  
import './components/globals.css';  

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Krysta Clone',
  description: 'Generated by Create Next App',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
